# .github/workflows/update-readme.yml

name: Update README with GitHub Blob URLs

on:
  push:
    paths:
      - 'coding_2025/meta/**'
  workflow_dispatch:  # also allow manual run

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Run generate_readme.py
        run: |
          python .github/scripts/generate_readme.py
        env:
          PYTHONPATH: .

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add your-folder/README.md
          git commit -m "Auto-update README.md with file list" || echo "No changes to commit"
          git push
